### ISSUE TITLE
取消main.sh之后，运行报错：unknown shorthand flag: 'd' in -docker exit status 1，求大佬帮看

### ISSUE THREAD

**Issue by levarsi** [gityzon/a-pg#1]
unknown shorthand flag: 'd' in -docker
exit status 1

**Comment by gityzlab** [comment]
原因：Alist V3新版 取消了启动命令 -docker
修复：commit 85e4205f578689c8d8e89964203dfcc957791d2d
未测试是否可行，若可行请回馈。

**Comment by levarsi** [comment]
unknown shorthand flag: 's' in -server
exit status 1
似乎也不行，我需要重装?

**Comment by levarsi** [comment]
误打误撞解决了。。
最后一行直接这样就行了，不需要带短杠，然后就启动成功了。。。
“./alist server”

**Comment by gityzlab** [comment]
All right. f02f9c1a8bb3e496f02522b418fa8800479834e8
